export const ADD_TODO = 'ADD_TODO'
export const ADD_TODO_FILTERING = 'ADD_TODO_FILTERING'
export const ADD_TODO_FAILED = 'ADD_TODOS_FAILED'

export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_TODO_FILTERING = 'DELETE_TODO_FILTERING'

export const FILTER_ALL = 'FILTER_ALL'
export const FILTER_COMPLETED = 'FILTER_COMPLETED'
export const FILTER_ACTIVE = 'FILTER_ACTIVE'

export const TOGGLE_TODO = 'TOGGLE_TODO'
export const TOGGLE_TODO_FILTERING = 'TOGGLE_TODO_FILTERING'

export const INIT_TODOS = 'INIT_TODOS'

export const CLEAR_ERROR = 'CLEAR_ERROR'
