export const ADD_TODO = 'ADD_TODO'
export const ADD_TODO_FILTERING = 'ADD_TODO_FILTERING'
export const ADD_TODO_FAILED = 'ADD_TODOS_FAILED'

export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_TODO_FILTERING = 'DELETE_TODO_FILTERING'

export const CLEAR_TODOS = 'CLEAR_TODOS'

export const FILTER_ALL = 'FILTER_ALL'
export const FILTER_COMPLETED = 'FILTER_COMPLETED'
export const FILTER_ACTIVE = 'FILTER_ACTIVE'

export const TOGGLE_TODO = 'TOGGLE_TODO'
export const TOGGLE_TODO_FILTERING = 'TOGGLE_TODO_FILTERING'

export const INIT_TODOS = 'INIT_TODOS'
export const INIT_TODOS_START = 'INIT_TODOS_START'
export const INIT_TODOS_FINISHED = 'INIT_TODOS_FINISHED'

export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SHOW_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const AUTH_START = 'AUTH_START'
export const AUTH_FINISH = 'AUTH_FINISH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const CLEAR_MODAL = 'CLEAR_MODAL'

export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS'

export const INIT_USER_DATA_SUCCESS = 'INIT_USER_DATA_SUCCESS'

export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'